// Auto-generated by scripts/process-images.mjs — do not edit manually.

export const imageManifest = [
  {
    "baseName": "Gemini_Generated_Image_4akgga4akgga4akg",
    "category": "disciplines",
    "originalDims": "1856×2304",
    "blurDataURL": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADwAwCdASoQABQAPxFysFAsJqSisAgBgCIJZQDCgCPpYBDwkwpVLFTAAP7o8iEF8Pgr+2mBzorY3kzAhzTGCQodpoAUoaFl7Kpf3DpPyOczGoHEfvEyKfe+xA3J7G+YxqgB/A74LXhwAA=="
  },
  {
    "baseName": "Gemini_Generated_Image_bfh8rkbfh8rkbfh8",
    "category": "disciplines",
    "originalDims": "1856×2304",
    "blurDataURL": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAAAwBACdASoQABQAPxFwsFAsJiSisAgBgCIJQBOgMZFRQJpDzMYq4fNrjwAA/tu8LgrJRSuIsoZMrQUhJiwhKFoKXRIEM66wafC6QT0rYjKZYuu1dPl7JpsXm1VUI1ru1As/+jxoDjlEXzpUJ8gq7muP4N9SGTcWV/CUYxlWraWOezXUEPmifww1QDhY7BQ7iYAAAA=="
  },
  {
    "baseName": "Gemini_Generated_Image_cdvli1cdvli1cdvl",
    "category": "disciplines",
    "originalDims": "1856×2304",
    "blurDataURL": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAAAwBACdASoQABQAPxFysFAsJqSisAgBgCIJaAAD5hoOG5Ma/eGJzfzIegAA/uw9asRYmxlpzyLld5V6EFraiADo1sbGM8I0fnes4wtrJ1um5ch+uApWkclGVJAKSzVflPZP5R0mNc83qGeDr2UZ9OaDnhpZk8A8muxyqXEWduZoMpgCg2/6iDnVE+sb+qgsAAA="
  },
  {
    "baseName": "Gemini_Generated_Image_l639hjl639hjl639",
    "category": "disciplines",
    "originalDims": "1856×2304",
    "blurDataURL": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAQBACdASoQABQAPxFysFAsJqSisAgBgCIJZQDA3BK4tvXHGzadHwKCAAD+n6YrC9v8PWptaE0AgfMGrGou2jgNTjhmWQIQtEE24QbGUTGMx6/8ZfygHnCh3lRCm6t+d5Tt6+S9G1LDJQbGBxrhUXiKalqRpvgA"
  },
  {
    "baseName": "Gemini_Generated_Image_nzyfjfnzyfjfnzyf",
    "category": "disciplines",
    "originalDims": "1856×2304",
    "blurDataURL": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAAAQBACdASoQABQAPxFwsFAsJiSisAgBgCIJQBadBHvkOWhIcta2eX/UAAD8Xjx+5isTMkyX8Trsodesu3+aIYxrQsQ7ZYNSZU2X4gihaGsPAVGYpEcOAZEN9kapv7XRZvrUJIbdxnXqFKfg95zy1ZWQfJ0AAA=="
  },
  {
    "baseName": "Gemini_Generated_Image_ridxmpridxmpridx",
    "category": "disciplines",
    "originalDims": "1856×2304",
    "blurDataURL": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAAAwBACdASoQABQAPxFysFAsJqSisAgBgCIJbAC7ACHetAXVKvL78VfUrAAA/uvt7NE0J7t+daCVGga/7XnP3NrkpxgvL8eU/zOOwVnrr2nO8ldEMNNgSNBlT9BGCSSJ5WydXFv7lY2AWPer7b3H9aeizE6m4JPpKStf6dDUa2Na/78/uUu07e4AAAA="
  },
  {
    "baseName": "Gemini_Generated_Image_sy6q1ysy6q1ysy6q",
    "category": "disciplines",
    "originalDims": "1856×2304",
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACQAwCdASoQABQAPxFwsFAsJiSisAgBgCIJYwC06B0sKIyvUZUAAP7jaF2lPHmTBV1mxS6JJPhaqifibT3nFKveOTnao9dVJENuAX0x+2C6+Lzf5OZGd5+GaUaizxAA"
  },
  {
    "baseName": "Gemini_Generated_Image_x5pr38x5pr38x5pr",
    "category": "disciplines",
    "originalDims": "1856×2304",
    "blurDataURL": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAAAQBACdASoQABQAPxFysFAsJqSisAgBgCIJbAC7MoADTszDbKdPBDrRiAD+6+3s0TQM44o9dgy+qU2A/fN38t6zETgxPdIzgVYrTUHneC6dtATRdKaAc22dB8Xe25Zi/tXnndKVtGvR6hc/QC0miHRu7l163Lr98X7tbGtf9+focpYGeoAAAA=="
  },
  {
    "baseName": "offers",
    "category": "disciplines",
    "originalDims": "1856×2304",
    "blurDataURL": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAABQBACdASoQABQAPxFysFAsJqSisAgBgCIJaACdAywBimfp5h0FAeobsHsAAP7jdrz1JPVg0H4jp1tEUps189dpwKxo+CouHi0vju6ZuQ0U8l340ViCzMWRelBmQpHF3lvJo/5L8W59SkFFcRu0oH/kLsqFpFiLNQWnOaLgNY94mYYAn0GSoAAA"
  },
  {
    "baseName": "parking",
    "category": "disciplines",
    "originalDims": "1856×2304",
    "blurDataURL": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADwAwCdASoQABQAPxFysFAsJqSisAgBgCIJQBhQAyS1kAzvBXxIf/IAAP7uoTBJIdm3xs0fsu3oGxIMDZIDrX8N6+i3PCe4tFt5zRYcvjXwE0Wi1nfr0vL73R1kdx1P7peh7RR5KyeCcUfHAAA="
  },
  {
    "baseName": "IMG_1384 copy",
    "category": "classes",
    "originalDims": "4160×6240",
    "blurDataURL": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAAAwBACdASoQABgAPxFysFCsJqSisAgBgCIJbAC7IExC+CcuOcnEPiWVcAAA/tzAN8DvOnq927foZlE7gjWGLx0hcNts1C40CgCXRupxCYRGPJkC66MWLsWDFAt8wD5RdLEInhn8GzLH5aHI7ZBWJnOhjX0aEEHI0hDOX9N96XnQEt2Yu0A6BWQK8I6McDK02DniaQdyiaIAAA=="
  },
  {
    "baseName": "2024-01-01 (1)",
    "category": "facility",
    "originalDims": "1020×1020",
    "blurDataURL": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAABwAgCdASoQABAABABoJbAC7AYtBoC/ueMtATsAAP7sW6i6DZw2b3O9FbSN+ZWvuTQVR2RD/c8vdcVWBFKqFk18er1FHu/jiPrenn0YqCvMO6NoU27LY0ylW6gWkN4qnNvuwaBpSdS3IxU3IZz9zK6EbgQAAA=="
  },
  {
    "baseName": "DSC01382",
    "category": "facility",
    "originalDims": "1360×909",
    "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAQCdASoQAAsABABoJbAC7AEf3F3nmcAA/vMC0/xZ9MA/EzuSWXfCYQH4/780B2b3AAAA"
  },
  {
    "baseName": "IMG_2609",
    "category": "facility",
    "originalDims": "6240×4160",
    "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAQCdASoQAAsABABoJbAC7AEN3smL+AAA/uzPyzfTk9j1PsP+5AfrwAYyPO6ifldJ0nkHdI5gzljYg9sID/Icfn9QjDpyP8q0wx3SbJA6bl6OhNnja5IAAAA="
  },
  {
    "baseName": "IMG_2613",
    "category": "facility",
    "originalDims": "6240×4160",
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAABQAgCdASoQAAsABABoJaACdAEVvO2zr9dXxAAA/uUJAHs9yhwb6Js0vNd2Acu9O2mRAZUyNnVvAYVnrpJ9eyb1Zh+EZdHlJ/Lu03dff7+bY47IAAA="
  },
  {
    "baseName": "red  ggffdd-Cover",
    "category": "hero",
    "originalDims": "3840×2160",
    "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoQAAkABABoJaAC7AD0gGi601AA/vWiHdi/gR1sWxBhMf/LfVs1soKfcmyhqZ7mMu9ssWmq9yRU+LAA"
  }
] as const;

export type ImageEntry = (typeof imageManifest)[number];

export function findImage(baseName: string): ImageEntry | undefined {
  return imageManifest.find((img) => img.baseName === baseName);
}
