import sharp from 'sharp';
import { readdir, mkdir, stat, writeFile } from 'fs/promises';
import path from 'path';

const SOURCE = 'source-assets/images';
const OUTPUT = 'public/images';

// Processing presets per category
const PRESETS = {
  hero:         { sizes: [{ w: 1920, suffix: '' }, { w: 1080, suffix: '-mobile' }], quality: 78 },
  facility:     { sizes: [{ w: 1600, suffix: '' }, { w: 800,  suffix: '-mobile' }], quality: 80 },
  classes:      { sizes: [{ w: 1200, suffix: '' }, { w: 800,  suffix: '-mobile' }], quality: 82 },
  disciplines:  { sizes: [{ w: 1200, suffix: '' }, { w: 720,  suffix: '-mobile' }], quality: 82 },
  'ai-generated': { sizes: [{ w: 1200, suffix: '' }, { w: 720,  suffix: '-mobile' }], quality: 82 },
};

async function processImage(srcPath, category, filename) {
  const baseName = path.basename(filename, path.extname(filename));
  const preset = PRESETS[category] || PRESETS.facility;

  // ai-generated maps to disciplines in output folder
  const outCategory = category === 'ai-generated' ? 'disciplines' : category;
  const outDir = path.join(OUTPUT, outCategory);
  await mkdir(outDir, { recursive: true });

  const meta = await sharp(srcPath).metadata();
  console.log(`  → ${filename} (${meta.width}×${meta.height})`);

  // Crop Gemini watermark if it's an ai-generated image (bottom-right ~60px)
  let basePipeline = sharp(srcPath);
  if (category === 'ai-generated') {
    const cropHeight = Math.max(0, meta.height - 80);
    basePipeline = basePipeline.extract({
      left: 0,
      top: 0,
      width: meta.width,
      height: cropHeight,
    });
  }

  for (const { w, suffix } of preset.sizes) {
    // WebP version
    await basePipeline
      .clone()
      .resize(w, null, { withoutEnlargement: true })
      .webp({ quality: preset.quality })
      .toFile(path.join(outDir, `${baseName}${suffix}.webp`));

    // AVIF version (smaller, modern browsers)
    await basePipeline
      .clone()
      .resize(w, null, { withoutEnlargement: true })
      .avif({ quality: preset.quality - 5 })
      .toFile(path.join(outDir, `${baseName}${suffix}.avif`));
  }

  // Blur placeholder (base64 data URL)
  const blurBuffer = await sharp(srcPath)
    .resize(16)
    .webp({ quality: 30 })
    .toBuffer();
  const blurDataURL = `data:image/webp;base64,${blurBuffer.toString('base64')}`;

  return {
    baseName,
    category: outCategory,
    originalDims: `${meta.width}×${meta.height}`,
    blurDataURL,
  };
}

async function main() {
  console.log('🖼️  Processing source images...\n');
  const categories = await readdir(SOURCE);
  const manifest = [];

  for (const category of categories) {
    const catPath = path.join(SOURCE, category);
    const stats = await stat(catPath);
    if (!stats.isDirectory()) continue;

    console.log(`📁 ${category}/`);
    const files = await readdir(catPath);

    for (const file of files) {
      if (!/\.(jpg|jpeg|png)$/i.test(file)) continue;
      try {
        const result = await processImage(path.join(catPath, file), category, file);
        manifest.push(result);
      } catch (err) {
        console.error(`    ❌ Failed: ${file} — ${err.message}`);
      }
    }
  }

  // Write manifest
  await mkdir('src/lib', { recursive: true });
  const tsContent = `// Auto-generated by scripts/process-images.mjs — do not edit manually.

export const imageManifest = ${JSON.stringify(manifest, null, 2)} as const;

export type ImageEntry = (typeof imageManifest)[number];

export function findImage(baseName: string): ImageEntry | undefined {
  return imageManifest.find((img) => img.baseName === baseName);
}
`;
  await writeFile('src/lib/image-manifest.ts', tsContent);
  console.log(`\n✅ Processed ${manifest.length} images`);
  console.log(`📝 Manifest written to src/lib/image-manifest.ts`);
}

main().catch((err) => {
  console.error('Fatal error:', err);
  process.exit(1);
});
