import sharp from 'sharp';
import { readdir, mkdir, stat, writeFile } from 'fs/promises';
import path from 'path';

const SOURCE = 'source-assets/images';
const OUTPUT = 'public/images';

// Processing presets per category
const PRESETS = {
  hero:         { sizes: [{ w: 1920, suffix: '' }, { w: 1080, suffix: '-mobile' }], quality: 78 },
  facility:     { sizes: [{ w: 1600, suffix: '' }, { w: 800,  suffix: '-mobile' }], quality: 80 },
  classes:      { sizes: [{ w: 1200, suffix: '' }, { w: 800,  suffix: '-mobile' }], quality: 82 },
  disciplines:  { sizes: [{ w: 1200, suffix: '' }, { w: 720,  suffix: '-mobile' }], quality: 82 },
  'ai-generated': { sizes: [{ w: 1200, suffix: '' }, { w: 720,  suffix: '-mobile' }], quality: 82 },
};

async function processImage(srcPath, category, filename) {
  const baseName = path.basename(filename, path.extname(filename));
  const preset = PRESETS[category] || PRESETS.facility;

  // ai-generated maps to disciplines in output folder
  const outCategory = category === 'ai-generated' ? 'disciplines' : category;
  const outDir = path.join(OUTPUT, outCategory);
  await mkdir(outDir, { recursive: true });

  const meta = await sharp(srcPath).metadata();
  console.log(`  → ${filename} (${meta.width}×${meta.height})`);

  // For ai-generated images, composite a black patch over the Gemini watermark
  // (bottom-right ~150px diamond logo area). Black matches the gym brand background
  // so the patch is invisible against dark UI sections.
  let sourceBuffer;
  if (category === 'ai-generated') {
    const wmSize = Math.min(150, Math.floor(meta.width * 0.1));
    const patchWidth = wmSize + 30;
    const patchHeight = wmSize + 30;
    const patchLeft = Math.max(0, meta.width - patchWidth);
    const patchTop = Math.max(0, meta.height - patchHeight);

    const blackPatch = Buffer.from(
      `<svg width="${patchWidth}" height="${patchHeight}"><rect width="100%" height="100%" fill="#0A0A0A"/></svg>`
    );

    sourceBuffer = await sharp(srcPath)
      .composite([{ input: blackPatch, top: patchTop, left: patchLeft }])
      .toBuffer();
  } else {
    sourceBuffer = await sharp(srcPath).toBuffer();
  }

  for (const { w, suffix } of preset.sizes) {
    await sharp(sourceBuffer)
      .resize(w, null, { withoutEnlargement: true })
      .webp({ quality: preset.quality })
      .toFile(path.join(outDir, `${baseName}${suffix}.webp`));

    await sharp(sourceBuffer)
      .resize(w, null, { withoutEnlargement: true })
      .avif({ quality: preset.quality - 5 })
      .toFile(path.join(outDir, `${baseName}${suffix}.avif`));
  }

  // Blur placeholder (from cleaned buffer)
  const blurBuffer = await sharp(sourceBuffer)
    .resize(16)
    .webp({ quality: 30 })
    .toBuffer();
  const blurDataURL = `data:image/webp;base64,${blurBuffer.toString('base64')}`;

  return {
    baseName,
    category: outCategory,
    originalDims: `${meta.width}×${meta.height}`,
    blurDataURL,
  };
}

async function main() {
  console.log('🖼️  Processing source images...\n');
  const categories = await readdir(SOURCE);
  const manifest = [];

  for (const category of categories) {
    if (category === 'coaches') {
      console.log(`⏭️  Skipping ${category}/ (Coaches page removed from plan)`);
      continue;
    }

    const catPath = path.join(SOURCE, category);
    const stats = await stat(catPath);
    if (!stats.isDirectory()) continue;

    console.log(`📁 ${category}/`);
    const files = await readdir(catPath);

    for (const file of files) {
      if (!/\.(jpg|jpeg|png)$/i.test(file)) continue;
      try {
        const result = await processImage(path.join(catPath, file), category, file);
        manifest.push(result);
      } catch (err) {
        console.error(`    ❌ Failed: ${file} — ${err.message}`);
      }
    }
  }

  // Write manifest
  await mkdir('src/lib', { recursive: true });
  const tsContent = `// Auto-generated by scripts/process-images.mjs — do not edit manually.

export const imageManifest = ${JSON.stringify(manifest, null, 2)} as const;

export type ImageEntry = (typeof imageManifest)[number];

export function findImage(baseName: string): ImageEntry | undefined {
  return imageManifest.find((img) => img.baseName === baseName);
}
`;
  await writeFile('src/lib/image-manifest.ts', tsContent);
  console.log(`\n✅ Processed ${manifest.length} images`);
  console.log(`📝 Manifest written to src/lib/image-manifest.ts`);
}

main().catch((err) => {
  console.error('Fatal error:', err);
  process.exit(1);
});
